import React from 'react';
import Col from 'react-bootstrap/Col';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import StudentTile from './StudentTile';

const StudentHome = ({ onOpenCases, onOpenEpma }) => {
  return (
    <div className="student-page">
      <Container className="mt-4 student-page__content">
        <div className="student-dashboard-shell">
          <div className="student-dashboard-header">
            <div>
              <h2 className="mb-2">Student workspace</h2>
              <p className="student-dashboard-header__copy mb-0">
                Choose a study route below to open revision cases or continue prescribing practice.
              </p>
            </div>
          </div>
          <Row className="g-4 mb-4">
            <Col lg={6}>
              <StudentTile
                title="Case studies"
                description="Open revision cases by topic, review completed sessions, and work through self-paced cases prepared by lecturers."
                icon="bi bi-journal-medical"
                onClick={onOpenCases}
                variant="blue"
              />
            </Col>
            <Col lg={6}>
              <StudentTile
                title="ePMA"
                description="Search for a training patient by NHS number, hospital number, or surname, or admit your own autogenerated test patient for practice."
                icon="bi bi-file-earmark-medical"
                onClick={onOpenEpma}
                variant="blue"
              />
            </Col>
          </Row>
        </div>
      </Container>
    </div>
  );
};

export default StudentHome;
